# Data Ethics, Equity and Justice

*“Responsible data science promotes best practices that maximize the availability of high quality data while limiting the potential for misuse that could erode fundamental rights and undermine the public trust in digital technologies.”*[-Digital Society](https://www.thedigitalsociety.info/themes/responsible-data-science/) 

## Ethics

Laws determine the legal parameters governing data use. But something that is legal can still be unethical and irresponsible. Here we imply the definition of **ethics** as the branch of knowledge establishing the fundamental principles of "right and wrong" behavior. These standards are informative, but not sufficient, for the appropriate management and use of data in today’s age of technology. 

## Equity

When practitioners talk about data ethics, we are often signaling the need for data equity. **Equity** is the process by which we work “toward fair outcomes for people or groups by treating them in ways that address their unique advantages or barriers” [(Hernandez, 2022)](./additional-materials/inclusive-language-mentoring-up.pdf). **Data equity** thus provides a lens for considering the multifaceted implications of how data are collected, processed, analyzed, interpreted, and distributed. It is helpful in understanding how data has been historically used to harm marginalized communities and communities of color. Data equity also allows opportunities for researchers to understand how marginalized communities have been adversely impacted by data misuse through racial bias, hyper surveillance, and stereotyping. 

## Justice

**Data justice** is often tied to data equity as an approach that [“redresses the ways of collecting and disseminating data that have invisibilized and harmed historically marginalized communities.”](https://www.coalitioncommunitiescolor.org/-why-research-data-justice) Data justice helps identify the role of data in maintaining systems of power and privilege, knowledge inequity, and harmful decision making. The pursuit of data justice can be a restorative process promoting fairness in how people are made visible and treated because of their digital data.

**In this workshop we will not debate ethics, equity, or justice. We invite you into this space with the explicit assumption that you seek to produce data-driven research benefiting society.** 

We assume you seek to use data science to generate knowledge while causing as little harm as possible. We aim to give you the intellectual tools to embed values of equity and justice into your own research by focusing on frameworks for responsible use of data and data science methodologies.